#RabbitMQ
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    exchange:
      name: event-exchange
    queue:
      name: event-notification-queue
    listener:
      simple:
        default-requeue-rejected: false


